# Generated by Django 4.2.7 on 2025-08-27 13:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('stress', 'Agricultural Stress'), ('crop_health', 'Crop Health'), ('water', 'Water Resources'), ('conflict_impact', 'Conflict Impact'), ('custom', 'Custom Analysis')], max_length=50)),
                ('time_period_start', models.DateField()),
                ('time_period_end', models.DateField()),
                ('content', models.JSONField(help_text='Report content structure in JSON format')),
                ('file_path', models.CharField(help_text='Path to generated report file', max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('regions', models.ManyToManyField(to='geospatial.region')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('stress', 'New Stress Detected'), ('conflict', 'New Conflict Event'), ('threshold', 'Index Threshold Breach'), ('change', 'Significant Land Use Change'), ('system', 'System Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
    ]
