# Generated by Django 4.2.7 on 2025-08-27 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
        ('reports_alerts', '0001_initial'),
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='regions',
            field=models.ManyToManyField(to='geospatial.region'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_conflict_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.conflictevent'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_stress_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.agriculturalstressevent'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'report_type'], name='reports_ale_organiz_f278d1_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['time_period_start', 'time_period_end'], name='reports_ale_time_pe_b12ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'alert_type'], name='reports_ale_organiz_bd85c1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='reports_ale_severit_e4c558_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read'], name='reports_ale_is_read_25f343_idx'),
        ),
    ]
