from django.db import models
from django.contrib.auth import get_user_model
from apps.users.models import TimeStampedModel
from apps.organizations.models import Organization
from apps.geospatial.models import Region
from apps.analytics.models import AgriculturalStressEvent, ConflictEvent
import uuid

User = get_user_model()


class Report(TimeStampedModel):
    """
    Generated reports for B2B clients.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    regions = models.ManyToManyField(Region)
    report_type = models.CharField(max_length=50, choices=(
        ('stress', 'Agricultural Stress'),
        ('crop_health', 'Crop Health'),
        ('water', 'Water Resources'),
        ('conflict_impact', 'Conflict Impact'),
        ('custom', 'Custom Analysis'),
    ))
    time_period_start = models.DateField()
    time_period_end = models.DateField()
    content = models.JSONField(help_text="Report content structure in JSON format")
    file_path = models.CharField(max_length=500, help_text="Path to generated report file")
    is_published = models.BooleanField(default=False)
    
    class Meta:
        indexes = [
            models.Index(fields=['organization', 'report_type']),
            models.Index(fields=['time_period_start', 'time_period_end']),
        ]
    
    def __str__(self):
        return f"{self.title} ({self.report_type}) for {self.organization.name}"


class Alert(TimeStampedModel):
    """
    Automated alerts generated by the system.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    regions = models.ManyToManyField(Region)
    alert_type = models.CharField(max_length=50, choices=(
        ('stress', 'New Stress Detected'),
        ('conflict', 'New Conflict Event'),
        ('threshold', 'Index Threshold Breach'),
        ('change', 'Significant Land Use Change'),
        ('system', 'System Alert'),
    ))
    severity = models.CharField(max_length=20, choices=(
        ('info', 'Information'),
        ('warning', 'Warning'),
        ('critical', 'Critical'),
    ))
    title = models.CharField(max_length=255)
    message = models.TextField()
    related_stress_event = models.ForeignKey(AgriculturalStressEvent, on_delete=models.SET_NULL, null=True, blank=True)
    related_conflict_event = models.ForeignKey(ConflictEvent, on_delete=models.SET_NULL, null=True, blank=True)
    is_read = models.BooleanField(default=False)
    read_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    read_at = models.DateTimeField(null=True, blank=True)
    
    class Meta:
        indexes = [
            models.Index(fields=['organization', 'alert_type']),
            models.Index(fields=['severity']),
            models.Index(fields=['is_read']),
        ]
    
    def __str__(self):
        return f"{self.severity} {self.alert_type} alert for {self.organization.name}: {self.title}"

