# Generated by Django 4.2.7 on 2025-08-27 13:09

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('intensity', models.IntegerField(help_text='Intensity level from 1 (minor) to 5 (major)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('affected_radius_km', models.FloatField(help_text='Estimated radius of impact in kilometers')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geospatial.region')),
            ],
            options={
                'indexes': [models.Index(fields=['region', 'event_date'], name='analytics_c_region__0005ca_idx'), models.Index(fields=['intensity'], name='analytics_c_intensi_c404ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgriculturalStressEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detection_date', models.DateField()),
                ('stress_type', models.CharField(choices=[('water', 'Water Stress'), ('disease', 'Disease/Pest'), ('nutrient', 'Nutrient Deficiency'), ('conflict', 'Conflict-Related'), ('other', 'Other')], max_length=50)),
                ('severity', models.IntegerField(help_text='Severity level from 1 (mild) to 5 (severe)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('affected_area_hectares', models.FloatField()),
                ('description', models.TextField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('crop_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geospatial.cropmapping')),
                ('evidence_indices', models.ManyToManyField(blank=True, to='geospatial.vegetationindex')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geospatial.region')),
            ],
            options={
                'indexes': [models.Index(fields=['region', 'detection_date'], name='analytics_a_region__8e636a_idx'), models.Index(fields=['stress_type'], name='analytics_a_stress__b5229d_idx'), models.Index(fields=['severity'], name='analytics_a_severit_a00d9e_idx')],
            },
        ),
    ]
