# Generated by Django 4.2.7 on 2025-08-27 13:09

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('typical_growing_season', models.JSONField(help_text='Start and end months for growing seasons')),
                ('optimal_ndvi_range', models.JSONField(help_text='Min and max NDVI values for healthy crop')),
                ('water_requirements', models.TextField(blank=True)),
                ('local_importance', models.TextField(blank=True, help_text='Description of importance to local food security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_hectares', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquisition_date', models.DateTimeField()),
                ('satellite_name', models.CharField(max_length=100)),
                ('cloud_cover_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resolution_meters', models.FloatField(help_text='Spatial resolution in meters')),
                ('bands_available', models.JSONField(help_text='List of available spectral bands')),
                ('image_path', models.CharField(help_text='Path to image file in storage', max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_images', to='geospatial.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('analyze', 'Analysis Access'), ('full', 'Full Access')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geospatial.region')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='organizations',
            field=models.ManyToManyField(through='geospatial.RegionAccess', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='CropMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_hectares', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.FloatField(help_text='Confidence level of crop classification (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mapping_date', models.DateField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geospatial.crop')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geospatial.region')),
            ],
        ),
        migrations.CreateModel(
            name='VegetationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index_type', models.CharField(choices=[('NDVI', 'Normalized Difference Vegetation Index'), ('EVI', 'Enhanced Vegetation Index'), ('NDWI', 'Normalized Difference Water Index'), ('SAVI', 'Soil Adjusted Vegetation Index')], max_length=20)),
                ('mean_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('std_deviation', models.FloatField()),
                ('raster_path', models.CharField(help_text='Path to processed raster file', max_length=500)),
                ('satellite_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_indices', to='geospatial.satelliteimage')),
            ],
            options={
                'indexes': [models.Index(fields=['index_type'], name='geospatial__index_t_8f55bc_idx')],
                'unique_together': {('satellite_image', 'index_type')},
            },
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['region', 'acquisition_date'], name='geospatial__region__9f29a4_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['satellite_name'], name='geospatial__satelli_0238c4_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['is_processed'], name='geospatial__is_proc_9f3ad5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='regionaccess',
            unique_together={('organization', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='cropmapping',
            unique_together={('region', 'crop', 'mapping_date')},
        ),
    ]
