# Generated by Django 4.2.7 on 2026-02-04 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'View Only'), ('analyze', 'Analysis Access'), ('full', 'Full Access')], default='view', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionaccess',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
