# Generated by Django 4.2.7 on 2026-02-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(help_text='Sentinel Hub Batch Request ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ANALYSING', 'Analysing'), ('ANALYSIS_DONE', 'Analysis Done'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial'), ('CANCELED', 'Canceled')], default='CREATED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('bbox', models.JSONField(help_text='Bounding box used [min_lon, min_lat, max_lon, max_lat]')),
                ('time_range_start', models.DateTimeField()),
                ('time_range_end', models.DateTimeField()),
                ('s3_bucket', models.CharField(max_length=100)),
                ('tile_count', models.IntegerField(default=0)),
                ('value_estimation', models.FloatField(blank=True, help_text='Estimated cost in PU', null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='geospatial.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
