# Generated by Django 4.2.7 on 2026-02-04 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_type', models.CharField(choices=[('stress_detection', 'Agricultural Stress Detection'), ('crop_classification', 'Crop Type Classification'), ('anomaly_detection', 'Anomaly Detection'), ('yield_prediction', 'Yield Prediction'), ('change_detection', 'Change Detection')], max_length=50)),
                ('algorithm', models.CharField(choices=[('random_forest', 'Random Forest'), ('isolation_forest', 'Isolation Forest'), ('svm', 'Support Vector Machine'), ('cnn', 'Convolutional Neural Network'), ('transformer', 'Transformer (PSETAE)'), ('autoencoder', 'Autoencoder'), ('ensemble', 'Ensemble Model')], max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('status', models.CharField(choices=[('training', 'Training'), ('trained', 'Trained'), ('deployed', 'Deployed'), ('failed', 'Training Failed'), ('deprecated', 'Deprecated')], default='training', max_length=20)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('preprocessing_pipeline', models.FileField(blank=True, null=True, upload_to='ml_models/preprocessing/')),
                ('feature_importance', models.FileField(blank=True, null=True, upload_to='ml_models/features/')),
                ('training_data_size', models.PositiveIntegerField(default=0)),
                ('training_date', models.DateTimeField(blank=True, null=True)),
                ('training_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('feature_names', models.JSONField(blank=True, default=list)),
                ('target_classes', models.JSONField(blank=True, default=list)),
                ('prediction_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('applicable_regions', models.ManyToManyField(blank=True, to='geospatial.region')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('training_config', models.JSONField(default=dict)),
                ('data_sources', models.JSONField(default=list)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('current_epoch', models.PositiveIntegerField(default=0)),
                ('total_epochs', models.PositiveIntegerField(default=0)),
                ('training_loss', models.FloatField(blank=True, null=True)),
                ('validation_loss', models.FloatField(blank=True, null=True)),
                ('training_metrics', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='ml_models.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_name', models.CharField(max_length=255)),
                ('importance_score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_importances', to='ml_models.mlmodel')),
            ],
            options={
                'ordering': ['model', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_features', models.JSONField()),
                ('input_data_hash', models.CharField(help_text='Hash of input data for deduplication', max_length=64)),
                ('prediction_result', models.JSONField()),
                ('prediction_confidence', models.FloatField(blank=True, null=True)),
                ('prediction_probabilities', models.JSONField(blank=True, default=dict)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=20)),
                ('ground_truth', models.JSONField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_models.mlmodel')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geospatial.region')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model', 'created_at'], name='ml_models_m_model_i_b6d466_idx'), models.Index(fields=['region', 'created_at'], name='ml_models_m_region__f55eba_idx'), models.Index(fields=['input_data_hash'], name='ml_models_m_input_d_fe5743_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('auc_score', models.FloatField(blank=True, null=True)),
                ('confusion_matrix', models.JSONField(blank=True, default=dict)),
                ('classification_report', models.JSONField(blank=True, default=dict)),
                ('evaluation_dataset', models.CharField(blank=True, max_length=255)),
                ('evaluation_date', models.DateField()),
                ('sample_size', models.PositiveIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='ml_models.mlmodel')),
            ],
            options={
                'ordering': ['-evaluation_date'],
                'unique_together': {('model', 'evaluation_date', 'evaluation_dataset')},
            },
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['model_type', 'status'], name='ml_models_m_model_t_452db1_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['algorithm'], name='ml_models_m_algorit_40c874_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['training_date'], name='ml_models_m_trainin_0b048b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureimportance',
            unique_together={('model', 'feature_name')},
        ),
    ]
