# Generated by Django 4.2.7 on 2025-08-27 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_keys_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('organization', 'key_name')},
        ),
        migrations.AddIndex(
            model_name='analyticslog',
            index=models.Index(fields=['organization', 'action_type'], name='api_keys_lo_organiz_6e6b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticslog',
            index=models.Index(fields=['created_at'], name='api_keys_lo_created_3f9531_idx'),
        ),
    ]
